# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/thewonderer619@gmail.com/proj1_pipeline")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM vsarthi_ws.default.sample_trips_proj1_pipeline"))

# COMMAND ----------

print(dbutils.fs.ls(f"abfss://ingestion@proj1sta.dfs.core.windows.net/customers/"))


# COMMAND ----------

# %sql 
# DROP TABLE IF EXISTS vsarthicat.proj1_pipeline.customer_stg

# COMMAND ----------

# MAGIC %sql
# MAGIC USE CATALOG vsarthicat;
# MAGIC USE SCHEMA proj1_pipeline;
# MAGIC

# COMMAND ----------

"vsarthicat.proj1_pipeline.customer_stg".printSchema()

# COMMAND ----------

# MAGIC %sql 
# MAGIC DESC vsarthicat.proj1_pipeline.customer_stg

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM vsarthicat.proj1_pipeline.products_stg

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM vsarthicat.proj1_pipeline.customer_silver;
